export const TELEGRAM_MAX_CONTENT_LENGTH = 500;
export const TELEGRAM_MAX_IMAGE_DIMENSIONS = 4000;
export const TELEGRAM_PREFER_IMAGE_WIDTH = 1200;
export const TELEGRAM_MAX_IMAGE_BYTES = 3_000_000;
export const TELEGRAM_ALLOWED_TAGS = [
  'b',
  'i',
  'u',
  's',
  'b',
  'a',
  'tg-emoji',
  'code',
  'pre',
  'strong',
  'em',
  'ins',
  'strike',
  'tg-spoiler',
];
export const TELEGRAM_DANGEROUSLY_HTML_TAG = 'body';
export const TELEGRAM_TAGS_TO_UNWRAP = [TELEGRAM_DANGEROUSLY_HTML_TAG];
export const TELEGRAM_IMAGE_BLACK_LIST_ENCODED = [
  'JUQwJTlGJUQxJTgzJUQxJTgyJUQxJTk2JUQwJUJE',
  'JUQwJTlGJUQxJTgzJUQxJTgyJUQwJUI4JUQwJUJE',
  'JUQwJTk4JUQwJUJDJUQwJUJGJUQwJUI1JUQxJTgwJUQwJUIwJUQxJTgyJUQwJUJFJUQxJTgwXyVEMCU5RCVEMCVCOCVEMCVCQSVEMCVCRSVEMCVCQiVEMCVCMCVEMCVCOV9JSQ==',
  'JUQwJTlGJUQwJUI1JUQxJTgyJUQxJTgwJUQwJUIwX0k=',
  'UHV0aW4=',
  'RmxhZ19vZl9SdXNzaWE=',
  'RmxhZ19vZl90aGVfU292aWV0',
  'UnVzc2lhbl9JbXBlcmlhbF9Bcm15',
  'Rm9yY2VzX29mX3RoZV9SdXNzaWFu',
  'RmxhZ19vZl9HZXJtYW55XyU1QygxOTM1JUUyJTgwJTkzMTk0NSU1Qyk=',
  'SGl0bGVy',
  'RmxhZ19vZl9Nb3Njb3c=',
  'YXJtc19vZl9SdXNzaWE=',
  'YXJtc19vZl90aGVfUnVzc2lhbg==',
  'Q29hdF9vZl9hcm1zX29mX3RoZV9Tb3ZpZXRfVW5pb24=',
  'JUQwJUExJUQwJUI1JUQwJUJEJUQwJUIwJUQxJTgyXyVEMCVBMCVEMCVCRSVEMSU4MSVEMSU5NiVEMCVCOSVEMSU4MSVEMSU4QyVEMCVCQSVEMCVCRSVEMSU5N18lRDElOTYlRDAlQkMlRDAlQkYlRDAlQjUlRDElODAlRDElOTYlRDElOTc=',
  'RW1ibGVtX29mX3RoZV9Va3JhaW5pYW5fU1NS',
  'RmxhZ19vZl90aGVfVWtyYWluaWFuX1NvdmlldF9Tb2NpYWxpc3RfUmVwdWJsaWM=',
  'Q29hdF9vZl9hcm1zX29mX01vc2Nvdw==',
  'RW1ibGVtYV9OS1ZE',
];
export const TELEGRAM_MAX_ON_THIS_DAY_TEXT = 600;
